"""
ArogyaPath Phase 9 — Lab Test Master seed data.
~60 tests across Haematology, Biochemistry, Clinical Pathology,
Serology & Immunology, Microbiology, Endocrinology, Tumor Markers,
Virology & Molecular.
"""

from arogyapath.arogyapath.seed_catalog import _p, _rr, _abx_urine, _abx_blood, _abx_sputum

LAB_TESTS = [

	# =====================================================================
	# HAEMATOLOGY
	# =====================================================================
	{
		"test_name": "Complete Blood Count (CBC / Hemogram)",
		"test_code": "CBC",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Automated 5-part differential cell counter",
		"tat_hours": 4,
		"cost": 250,
		"report_format": "Standard",
		"methodology_note": "Performed on automated hematology analyzer with 5-part differential.",
		"parameters": [
			_p("Haemoglobin", "HB", "g/dL", order=1, heading="Complete Blood Count", bold=1, decimals=1),
			_p("Total RBC Count", "RBC", "×10⁶/µL", order=2, heading="Complete Blood Count", decimals=2),
			_p("Total WBC (TLC)", "WBC", "×10³/µL", order=3, heading="Complete Blood Count", decimals=2),
			_p("Platelet Count", "PLT", "×10³/µL", order=4, heading="Complete Blood Count", decimals=0),
			_p("Haematocrit (PCV)", "HCT", "%", order=5, heading="Complete Blood Count", decimals=1),
			_p("MCV", "MCV", "fL", order=6, heading="Red Cell Indices", decimals=1),
			_p("MCH", "MCH", "pg", order=7, heading="Red Cell Indices", decimals=1),
			_p("MCHC", "MCHC", "g/dL", order=8, heading="Red Cell Indices", decimals=1),
			_p("RDW-CV", "RDW", "%", order=9, heading="Red Cell Indices", decimals=1),
			_p("Mean Platelet Volume (MPV)", "MPV", "fL", order=10, heading="Platelet Indices", decimals=1),
			_p("Neutrophils", "NEU", "%", order=11, heading="Differential Count", decimals=1),
			_p("Lymphocytes", "LYM", "%", order=12, heading="Differential Count", decimals=1),
			_p("Monocytes", "MONO", "%", order=13, heading="Differential Count", decimals=1),
			_p("Eosinophils", "EOS", "%", order=14, heading="Differential Count", decimals=1),
			_p("Basophils", "BASO", "%", order=15, heading="Differential Count", decimals=1),
			_p("Absolute Neutrophil Count", "ANC", "×10³/µL", order=16, heading="Absolute Count",
			   decimals=2, calc=1, formula="WBC * NEU / 100"),
			_p("Absolute Lymphocyte Count", "ALC", "×10³/µL", order=17, heading="Absolute Count",
			   decimals=2, calc=1, formula="WBC * LYM / 100"),
		],
		"reference_ranges": [
			_rr("Haemoglobin", "Male",   nmin=13.0, nmax=17.0, cmin=7.0, cmax=20.0, display="13.0–17.0"),
			_rr("Haemoglobin", "Female", nmin=12.0, nmax=15.0, cmin=7.0, cmax=20.0, display="12.0–15.0"),
			_rr("Total WBC (TLC)", nmin=4.0, nmax=11.0, cmin=2.0, cmax=30.0, display="4.0–11.0"),
			_rr("Platelet Count", nmin=150, nmax=400, cmin=50, cmax=1000, display="150–400"),
			_rr("Total RBC Count", "Male",   nmin=4.5, nmax=5.5, display="4.5–5.5"),
			_rr("Total RBC Count", "Female", nmin=4.0, nmax=5.0, display="4.0–5.0"),
			_rr("Haematocrit (PCV)", "Male",   nmin=40, nmax=52, display="40–52"),
			_rr("Haematocrit (PCV)", "Female", nmin=36, nmax=46, display="36–46"),
			_rr("MCV", nmin=80, nmax=100, display="80–100"),
			_rr("MCH", nmin=27, nmax=32, display="27–32"),
			_rr("MCHC", nmin=32, nmax=36, display="32–36"),
			_rr("RDW-CV", nmin=11.5, nmax=14.5, display="11.5–14.5"),
			_rr("Mean Platelet Volume (MPV)", nmin=7.5, nmax=12.5, display="7.5–12.5"),
			_rr("Neutrophils", nmin=40, nmax=70, display="40–70"),
			_rr("Lymphocytes", nmin=20, nmax=40, display="20–40"),
			_rr("Monocytes", nmin=2, nmax=10, display="2–10"),
			_rr("Eosinophils", nmin=1, nmax=6, display="1–6"),
			_rr("Basophils", nmin=0, nmax=1, display="0–1"),
		],
	},

	{
		"test_name": "ESR (Erythrocyte Sedimentation Rate)",
		"test_code": "ESR",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Westergren Method",
		"tat_hours": 2,
		"cost": 100,
		"report_format": "Standard",
		"parameters": [_p("ESR (1 Hour)", "ESR1H", "mm/hr", order=1, decimals=0)],
		"reference_ranges": [
			_rr("ESR (1 Hour)", "Male",   nmin=0, nmax=15, display="0–15"),
			_rr("ESR (1 Hour)", "Female", nmin=0, nmax=20, display="0–20"),
		],
	},

	{
		"test_name": "Haemoglobin",
		"test_code": "HB",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Cyanmethaemoglobin / Automated",
		"tat_hours": 2,
		"cost": 100,
		"report_format": "Standard",
		"parameters": [_p("Haemoglobin", "HB", "g/dL", order=1, decimals=1)],
		"reference_ranges": [
			_rr("Haemoglobin", "Male",   nmin=13.0, nmax=17.0, cmin=7.0, cmax=20.0),
			_rr("Haemoglobin", "Female", nmin=12.0, nmax=15.0, cmin=7.0, cmax=20.0),
		],
	},

	{
		"test_name": "Prothrombin Time (PT/INR)",
		"test_code": "PTINR",
		"department": "Haematology",
		"sample_type": "Plasma (Citrate)",
		"method": "Photo-optical clot detection",
		"tat_hours": 4,
		"cost": 250,
		"report_format": "Standard",
		"parameters": [
			_p("PT Patient", "PT_PAT", "seconds", order=1, decimals=1),
			_p("PT Control", "PT_CTL", "seconds", order=2, decimals=1),
			_p("INR", "INR", "INR", order=3, bold=1, decimals=2),
			_p("Prothrombin Activity", "PT_ACT", "%", order=4, decimals=1),
		],
		"reference_ranges": [
			_rr("PT Patient", nmin=11, nmax=14, display="11–14"),
			_rr("INR", nmin=0.8, nmax=1.2, cmin=0.5, cmax=5.0, display="0.8–1.2"),
		],
	},

	{
		"test_name": "APTT (Activated Partial Thromboplastin Time)",
		"test_code": "APTT",
		"department": "Haematology",
		"sample_type": "Plasma (Citrate)",
		"method": "Photo-optical clot detection",
		"tat_hours": 4,
		"cost": 250,
		"report_format": "Standard",
		"parameters": [
			_p("APTT Patient", "APTT_PAT", "seconds", order=1, decimals=1),
			_p("APTT Control", "APTT_CTL", "seconds", order=2, decimals=1),
			_p("APTT Ratio", "APTT_R", order=3, decimals=2, calc=1, formula="APTT_PAT / APTT_CTL"),
		],
		"reference_ranges": [
			_rr("APTT Patient", nmin=25, nmax=38, display="25–38"),
			_rr("APTT Ratio", nmin=0.8, nmax=1.2, display="0.8–1.2"),
		],
	},

	{
		"test_name": "Peripheral Blood Smear",
		"test_code": "PBS",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Leishman Stain / Manual Microscopy",
		"tat_hours": 6,
		"cost": 200,
		"report_format": "Microscopy",
		"parameters": [
			_p("RBC Morphology", "RBC_MORPH", rtype="Text", order=1),
			_p("WBC Morphology", "WBC_MORPH", rtype="Text", order=2),
			_p("Platelet Morphology", "PLT_MORPH", rtype="Text", order=3),
			_p("Impression", "PBS_IMP", rtype="Text", order=4, bold=1),
		],
		"reference_ranges": [
			_rr("RBC Morphology", normal_text="Normocytic Normochromic"),
			_rr("WBC Morphology", normal_text="No abnormal cells seen"),
			_rr("Platelet Morphology", normal_text="Adequate in number and morphology"),
		],
	},

	{
		"test_name": "Reticulocyte Count",
		"test_code": "RETIC",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Supravital stain / Automated",
		"tat_hours": 4,
		"cost": 200,
		"report_format": "Standard",
		"parameters": [
			_p("Reticulocyte %", "RETIC_PCT", "%", order=1, decimals=2),
			_p("Absolute Reticulocyte Count", "RETIC_ABS", "×10³/µL", order=2, decimals=0),
		],
		"reference_ranges": [_rr("Reticulocyte %", nmin=0.5, nmax=2.5, display="0.5–2.5")],
	},

	{
		"test_name": "Malaria Parasite (Rapid Card Test)",
		"test_code": "MP",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Rapid ICT (HRP2 / pLDH)",
		"tat_hours": 1,
		"cost": 300,
		"report_format": "Standard",
		"parameters": [
			_p("P. falciparum (HRP2)", "MP_PF", rtype="Positive-Negative", order=1),
			_p("P. vivax (pLDH)", "MP_PV", rtype="Positive-Negative", order=2),
			_p("Interpretation", "MP_INTERP", rtype="Text", order=3, bold=1),
		],
		"reference_ranges": [
			_rr("P. falciparum (HRP2)", normal_text="Negative"),
			_rr("P. vivax (pLDH)",      normal_text="Negative"),
		],
	},

	{
		"test_name": "G6PD (Glucose-6-Phosphate Dehydrogenase)",
		"test_code": "G6PD",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Fluorescent Spot / Quantitative Spectrophotometry",
		"tat_hours": 24,
		"cost": 500,
		"report_format": "Standard",
		"parameters": [
			_p("G6PD Activity", "G6PD_ACT", "U/gHb", order=1, decimals=1),
			_p("Interpretation", "G6PD_INTERP", rtype="Multiple Choice", order=2,
			   options="Normal\nMildly Deficient\nModerately Deficient\nSeverely Deficient"),
		],
		"reference_ranges": [_rr("G6PD Activity", nmin=6.97, nmax=20.5, display="6.97–20.5")],
	},

	# =====================================================================
	# BIOCHEMISTRY
	# =====================================================================
	{
		"test_name": "Liver Function Test (LFT)",
		"test_code": "LFT",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Fully Automated Spectrophotometry",
		"tat_hours": 6,
		"cost": 600,
		"report_format": "Standard",
		"parameters": [
			_p("Bilirubin Total", "BIL_T", "mg/dL", order=1, heading="Bilirubin", bold=1, decimals=2),
			_p("Bilirubin Direct", "BIL_D", "mg/dL", order=2, heading="Bilirubin", decimals=2),
			_p("Bilirubin Indirect", "BIL_I", "mg/dL", order=3, heading="Bilirubin", decimals=2,
			   calc=1, formula="BIL_T - BIL_D"),
			_p("SGPT (ALT)", "ALT", "IU/L", order=4, heading="Liver Enzymes", bold=1, decimals=0),
			_p("SGOT (AST)", "AST", "IU/L", order=5, heading="Liver Enzymes", bold=1, decimals=0),
			_p("AST/ALT Ratio", "AST_ALT", order=6, heading="Liver Enzymes", decimals=2,
			   calc=1, formula="AST / ALT"),
			_p("Alkaline Phosphatase (ALP)", "ALP", "IU/L", order=7, heading="Liver Enzymes", decimals=0),
			_p("GGT", "GGT", "IU/L", order=8, heading="Liver Enzymes", decimals=0),
			_p("Total Protein", "TP", "g/dL", order=9, heading="Proteins", bold=1, decimals=1),
			_p("Serum Albumin", "ALB", "g/dL", order=10, heading="Proteins", decimals=1),
			_p("Globulin", "GLOB", "g/dL", order=11, heading="Proteins", decimals=1,
			   calc=1, formula="TP - ALB"),
			_p("A/G Ratio", "AG", order=12, heading="Proteins", decimals=2,
			   calc=1, formula="ALB / GLOB"),
		],
		"reference_ranges": [
			_rr("Bilirubin Total",   nmin=0.2, nmax=1.2, cmin=None, cmax=15, display="0.2–1.2"),
			_rr("Bilirubin Direct",  nmin=0.0, nmax=0.4, display="0.0–0.4"),
			_rr("Bilirubin Indirect",nmin=0.1, nmax=0.8, display="0.1–0.8"),
			_rr("SGPT (ALT)", "Male",   nmin=7, nmax=56, cmin=None, cmax=500, display="7–56"),
			_rr("SGPT (ALT)", "Female", nmin=7, nmax=45, cmin=None, cmax=500, display="7–45"),
			_rr("SGOT (AST)", nmin=10, nmax=40, cmin=None, cmax=500, display="10–40"),
			_rr("Alkaline Phosphatase (ALP)", nmin=44, nmax=147, display="44–147"),
			_rr("GGT", "Male",   nmin=10, nmax=71, display="10–71"),
			_rr("GGT", "Female", nmin=6,  nmax=42, display="6–42"),
			_rr("Total Protein", nmin=6.4, nmax=8.3, display="6.4–8.3"),
			_rr("Serum Albumin", nmin=3.5, nmax=5.0, cmin=2.0, cmax=None, display="3.5–5.0"),
		],
	},

	{
		"test_name": "Kidney Function Test (KFT / RFT)",
		"test_code": "KFT",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Automated Spectrophotometry + ISE",
		"tat_hours": 6,
		"cost": 550,
		"report_format": "Standard",
		"parameters": [
			_p("Blood Urea Nitrogen (BUN)", "BUN", "mg/dL", order=1, heading="Renal", decimals=1),
			_p("Serum Urea", "UREA", "mg/dL", order=2, heading="Renal", decimals=1),
			_p("Serum Creatinine", "CREAT", "mg/dL", order=3, heading="Renal", bold=1, decimals=2),
			_p("eGFR (MDRD)", "EGFR", "mL/min/1.73m²", order=4, heading="Renal", decimals=1,
			   calc=1, formula="175 * (CREAT ** -1.154) * 35"),
			_p("BUN/Creatinine Ratio", "BUN_CR", order=5, heading="Renal", decimals=1,
			   calc=1, formula="BUN / CREAT"),
			_p("Serum Uric Acid", "UA", "mg/dL", order=6, heading="Renal", decimals=1),
			_p("Serum Sodium (Na)", "NA", "mEq/L", order=7, heading="Electrolytes", bold=1, decimals=1),
			_p("Serum Potassium (K)", "K", "mEq/L", order=8, heading="Electrolytes", bold=1, decimals=1),
			_p("Serum Chloride (Cl)", "CL", "mEq/L", order=9, heading="Electrolytes", decimals=1),
			_p("Serum Calcium", "CA", "mg/dL", order=10, heading="Minerals", decimals=1),
			_p("Serum Phosphorus", "PHOS", "mg/dL", order=11, heading="Minerals", decimals=1),
		],
		"reference_ranges": [
			_rr("Blood Urea Nitrogen (BUN)", nmin=7,  nmax=20, display="7–20"),
			_rr("Serum Urea", nmin=15, nmax=45, display="15–45"),
			_rr("Serum Creatinine", "Male",   nmin=0.7, nmax=1.3, cmin=None, cmax=10, display="0.7–1.3"),
			_rr("Serum Creatinine", "Female", nmin=0.6, nmax=1.1, cmin=None, cmax=10, display="0.6–1.1"),
			_rr("eGFR (MDRD)", nmin=60, nmax=None, cmin=15, cmax=None, display=">60"),
			_rr("Serum Uric Acid", "Male",   nmin=3.5, nmax=7.2, display="3.5–7.2"),
			_rr("Serum Uric Acid", "Female", nmin=2.6, nmax=6.0, display="2.6–6.0"),
			_rr("Serum Sodium (Na)", nmin=135, nmax=145, cmin=120, cmax=160, display="135–145"),
			_rr("Serum Potassium (K)", nmin=3.5, nmax=5.1, cmin=2.5, cmax=6.5, display="3.5–5.1"),
			_rr("Serum Chloride (Cl)", nmin=98, nmax=107, display="98–107"),
			_rr("Serum Calcium", nmin=8.5, nmax=10.5, cmin=6.5, cmax=13, display="8.5–10.5"),
			_rr("Serum Phosphorus", nmin=2.5, nmax=4.5, display="2.5–4.5"),
		],
	},

	{
		"test_name": "Lipid Profile",
		"test_code": "LIPID",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Enzymatic Colorimetric / Automated",
		"tat_hours": 6,
		"cost": 550,
		"methodology_note": "Fasting 10-12 hours required.",
		"report_format": "Standard",
		"parameters": [
			_p("Total Cholesterol", "TC", "mg/dL", order=1, bold=1, decimals=0),
			_p("Triglycerides", "TG", "mg/dL", order=2, bold=1, decimals=0),
			_p("HDL Cholesterol", "HDL", "mg/dL", order=3, bold=1, decimals=0),
			_p("LDL Cholesterol", "LDL", "mg/dL", order=4, bold=1, decimals=0,
			   calc=1, formula="TC - HDL - TG / 5"),
			_p("VLDL Cholesterol", "VLDL", "mg/dL", order=5, decimals=0,
			   calc=1, formula="TG / 5"),
			_p("Non-HDL Cholesterol", "NONHDL", "mg/dL", order=6, decimals=0,
			   calc=1, formula="TC - HDL"),
			_p("LDL/HDL Ratio", "LDL_HDL", order=7, decimals=2, calc=1, formula="LDL / HDL"),
			_p("TC/HDL Ratio", "TC_HDL", order=8, decimals=2, calc=1, formula="TC / HDL"),
			_p("TG/HDL Ratio", "TG_HDL", order=9, decimals=2, calc=1, formula="TG / HDL"),
		],
		"reference_ranges": [
			_rr("Total Cholesterol",  nmin=None, nmax=200, cmin=None, cmax=300, display="Desirable: <200"),
			_rr("Triglycerides",      nmin=None, nmax=150, cmin=None, cmax=500, display="Normal: <150"),
			_rr("HDL Cholesterol", "Male",   nmin=40, nmax=None, display=">40 (Low risk: >60)"),
			_rr("HDL Cholesterol", "Female", nmin=50, nmax=None, display=">50 (Low risk: >60)"),
			_rr("LDL Cholesterol",    nmin=None, nmax=100, display="Optimal: <100"),
			_rr("VLDL Cholesterol",   nmin=2, nmax=30, display="2–30"),
			_rr("LDL/HDL Ratio",      nmin=None, nmax=3.5, display="<3.5"),
			_rr("TC/HDL Ratio",       nmin=None, nmax=4.5, display="<4.5"),
		],
	},

	{
		"test_name": "Blood Glucose Fasting (FBS)",
		"test_code": "GLUF",
		"department": "Biochemistry",
		"sample_type": "Plasma (Fluoride)",
		"method": "Glucose Oxidase / Hexokinase",
		"tat_hours": 2,
		"cost": 80,
		"methodology_note": "Fasting 8-12 hours required.",
		"report_format": "Standard",
		"parameters": [_p("Blood Glucose Fasting", "GLUF", "mg/dL", order=1, decimals=0)],
		"reference_ranges": [
			_rr("Blood Glucose Fasting", nmin=70, nmax=100, cmin=40, cmax=500,
				display="Normal: 70–100 | Pre-diabetic: 100–125 | Diabetic: ≥126"),
		],
	},

	{
		"test_name": "Blood Glucose Post Prandial (PPBS)",
		"test_code": "GLUPP",
		"department": "Biochemistry",
		"sample_type": "Plasma (Fluoride)",
		"method": "Glucose Oxidase / Hexokinase",
		"tat_hours": 2,
		"cost": 80,
		"methodology_note": "Collected exactly 2 hours after a full meal.",
		"report_format": "Standard",
		"parameters": [_p("Blood Glucose PP", "GLUPP", "mg/dL", order=1, decimals=0)],
		"reference_ranges": [
			_rr("Blood Glucose PP", nmin=None, nmax=140, cmin=40, cmax=500,
				display="Normal: <140 | Pre-diabetic: 140–199 | Diabetic: ≥200"),
		],
	},

	{
		"test_name": "Blood Glucose Random (RBS)",
		"test_code": "GLUR",
		"department": "Biochemistry",
		"sample_type": "Plasma (Fluoride)",
		"method": "Glucose Oxidase",
		"tat_hours": 1,
		"cost": 80,
		"report_format": "Standard",
		"parameters": [_p("Blood Glucose Random", "GLUR", "mg/dL", order=1, decimals=0)],
		"reference_ranges": [
			_rr("Blood Glucose Random", nmin=70, nmax=140, cmin=40, cmax=500,
				display="Normal: 70–140 | Diabetic (with symptoms): ≥200"),
		],
	},

	{
		"test_name": "HbA1c (Glycated Haemoglobin)",
		"test_code": "HBA1C",
		"department": "Biochemistry",
		"sample_type": "Whole Blood (EDTA)",
		"method": "HPLC / Immunoturbidimetry",
		"tat_hours": 6,
		"cost": 400,
		"report_format": "Standard",
		"parameters": [
			_p("HbA1c", "HBA1C", "%", order=1, bold=1, decimals=1),
			_p("Est. Average Glucose (eAG)", "EAG", "mg/dL", order=2, decimals=0,
			   calc=1, formula="28.7 * HBA1C - 46.7"),
		],
		"reference_ranges": [
			_rr("HbA1c", nmin=None, nmax=5.7, cmin=None, cmax=15,
				display="Normal: <5.7% | Pre-diabetic: 5.7–6.4% | Diabetic: ≥6.5%"),
		],
	},

	{
		"test_name": "Iron Studies",
		"test_code": "IRON",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Colorimetric / Immunoturbidimetry",
		"tat_hours": 6,
		"cost": 550,
		"report_format": "Standard",
		"parameters": [
			_p("Serum Iron", "IRON", "µg/dL", order=1, bold=1, decimals=0),
			_p("UIBC", "UIBC", "µg/dL", order=2, decimals=0),
			_p("TIBC", "TIBC", "µg/dL", order=3, decimals=0, calc=1, formula="IRON + UIBC"),
			_p("Transferrin Saturation", "TSAT", "%", order=4, decimals=1,
			   calc=1, formula="IRON / TIBC * 100"),
		],
		"reference_ranges": [
			_rr("Serum Iron", "Male",   nmin=65, nmax=175, display="65–175"),
			_rr("Serum Iron", "Female", nmin=50, nmax=170, display="50–170"),
			_rr("TIBC", nmin=250, nmax=370, display="250–370"),
			_rr("Transferrin Saturation", "Male",   nmin=20, nmax=50, display="20–50"),
			_rr("Transferrin Saturation", "Female", nmin=15, nmax=50, display="15–50"),
		],
	},

	{
		"test_name": "Ferritin",
		"test_code": "FERR",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 6,
		"cost": 450,
		"report_format": "Standard",
		"parameters": [_p("Serum Ferritin", "FERR", "ng/mL", order=1, decimals=1)],
		"reference_ranges": [
			_rr("Serum Ferritin", "Male",   nmin=24, nmax=336, display="24–336"),
			_rr("Serum Ferritin", "Female", nmin=11, nmax=307, display="11–307"),
		],
	},

	{
		"test_name": "Vitamin D3 (25-OH Vitamin D)",
		"test_code": "VITD",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [
			_p("25-OH Vitamin D", "VITD", "ng/mL", order=1, bold=1, decimals=1),
			_p("Interpretation", "VITD_INTERP", rtype="Multiple Choice", order=2,
			   options="Deficient (<20)\nInsufficient (20-29)\nSufficient (30-100)\nToxic (>100)"),
		],
		"reference_ranges": [
			_rr("25-OH Vitamin D", nmin=30, nmax=100, cmin=None, cmax=150,
				display="Sufficient: 30–100 | Insufficient: 20–29 | Deficient: <20"),
		],
	},

	{
		"test_name": "Vitamin B12 (Cobalamin)",
		"test_code": "VITB12",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Vitamin B12", "VITB12", "pg/mL", order=1, bold=1, decimals=0)],
		"reference_ranges": [
			_rr("Vitamin B12", nmin=200, nmax=900, cmin=100, cmax=None,
				display="Normal: 200–900 | Deficient: <200"),
		],
	},

	{
		"test_name": "Folic Acid (Folate)",
		"test_code": "FOLATE",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 600,
		"report_format": "Standard",
		"parameters": [_p("Serum Folate", "FOLATE", "ng/mL", order=1, decimals=1)],
		"reference_ranges": [_rr("Serum Folate", nmin=3.1, nmax=17.5, display="3.1–17.5")],
	},

	{
		"test_name": "C-Reactive Protein (CRP) Quantitative",
		"test_code": "CRP",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Immunoturbidimetry",
		"tat_hours": 4,
		"cost": 400,
		"report_format": "Standard",
		"parameters": [_p("CRP", "CRP", "mg/L", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("CRP", nmin=None, nmax=6.0, display="Normal: <6.0 | Mild: 6–50 | Severe: >50"),
		],
	},

	{
		"test_name": "hs-CRP (High Sensitivity CRP)",
		"test_code": "HSCRP",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Latex-enhanced Immunoturbidimetry",
		"tat_hours": 6,
		"cost": 600,
		"report_format": "Standard",
		"parameters": [_p("hs-CRP", "HSCRP", "mg/L", order=1, bold=1, decimals=3)],
		"reference_ranges": [
			_rr("hs-CRP", nmin=None, nmax=1.0,
				display="Low risk: <1.0 | Average: 1–3 | High risk: >3"),
		],
	},

	{
		"test_name": "Electrolytes (Na / K / Cl)",
		"test_code": "ELEC",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Ion Selective Electrode (ISE)",
		"tat_hours": 4,
		"cost": 350,
		"report_format": "Standard",
		"parameters": [
			_p("Serum Sodium (Na)", "NA", "mEq/L", order=1, bold=1, decimals=1),
			_p("Serum Potassium (K)", "K", "mEq/L", order=2, bold=1, decimals=1),
			_p("Serum Chloride (Cl)", "CL", "mEq/L", order=3, decimals=1),
		],
		"reference_ranges": [
			_rr("Serum Sodium (Na)",  nmin=135, nmax=145, cmin=120, cmax=160, display="135–145"),
			_rr("Serum Potassium (K)",nmin=3.5, nmax=5.1, cmin=2.5, cmax=6.5, display="3.5–5.1"),
			_rr("Serum Chloride (Cl)",nmin=98,  nmax=107, display="98–107"),
		],
	},

	{
		"test_name": "Serum Uric Acid",
		"test_code": "UA",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Enzymatic Colorimetric (Uricase)",
		"tat_hours": 4,
		"cost": 150,
		"report_format": "Standard",
		"parameters": [_p("Serum Uric Acid", "UA", "mg/dL", order=1, decimals=1)],
		"reference_ranges": [
			_rr("Serum Uric Acid", "Male",   nmin=3.5, nmax=7.2, display="3.5–7.2"),
			_rr("Serum Uric Acid", "Female", nmin=2.6, nmax=6.0, display="2.6–6.0"),
		],
	},

	{
		"test_name": "Serum Calcium",
		"test_code": "CA",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Colorimetric (Arsenazo III)",
		"tat_hours": 4,
		"cost": 150,
		"report_format": "Standard",
		"parameters": [_p("Serum Calcium", "CA", "mg/dL", order=1, decimals=1)],
		"reference_ranges": [
			_rr("Serum Calcium", nmin=8.5, nmax=10.5, cmin=6.5, cmax=13.5, display="8.5–10.5"),
		],
	},

	{
		"test_name": "Amylase",
		"test_code": "AMYLASE",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Enzymatic (CNPG3)",
		"tat_hours": 4,
		"cost": 300,
		"report_format": "Standard",
		"parameters": [_p("Serum Amylase", "AMYLASE", "U/L", order=1, decimals=0)],
		"reference_ranges": [_rr("Serum Amylase", nmin=28, nmax=100, display="28–100")],
	},

	{
		"test_name": "Lipase",
		"test_code": "LIPASE",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Enzymatic Colorimetric",
		"tat_hours": 4,
		"cost": 400,
		"report_format": "Standard",
		"parameters": [_p("Serum Lipase", "LIPASE", "U/L", order=1, decimals=0)],
		"reference_ranges": [_rr("Serum Lipase", nmin=13, nmax=60, cmin=None, cmax=600, display="13–60")],
	},

	{
		"test_name": "D-Dimer",
		"test_code": "DDIMER",
		"department": "Biochemistry",
		"sample_type": "Plasma (Citrate)",
		"method": "Immunoturbidimetry (LFIA)",
		"tat_hours": 4,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [_p("D-Dimer", "DDIMER", "µg/mL FEU", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("D-Dimer", nmin=None, nmax=0.5, cmin=None, cmax=10,
				display="Normal: <0.5 µg/mL FEU"),
		],
	},

	{
		"test_name": "Troponin I (Cardiac)",
		"test_code": "TROPI",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 2,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("Troponin I", "TROPI", "ng/mL", order=1, bold=1, decimals=3)],
		"reference_ranges": [
			_rr("Troponin I", nmin=None, nmax=0.04, cmin=None, cmax=100,
				display="Normal: <0.04 | Probable MI: 0.04–2.0 | AMI: >2.0"),
		],
	},

	{
		"test_name": "CPK-MB (Creatine Kinase MB)",
		"test_code": "CPKMB",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / Immunoinhibition",
		"tat_hours": 4,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [
			_p("CPK-MB", "CPKMB", "U/L", order=1, decimals=0),
			_p("CPK Total", "CPKT", "U/L", order=2, decimals=0),
		],
		"reference_ranges": [
			_rr("CPK-MB", nmin=None, nmax=25, display="<25"),
			_rr("CPK Total", "Male",   nmin=38, nmax=174, display="38–174"),
			_rr("CPK Total", "Female", nmin=26, nmax=140, display="26–140"),
		],
	},

	{
		"test_name": "Homocysteine",
		"test_code": "HOMO",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [_p("Homocysteine", "HOMO", "µmol/L", order=1, decimals=1)],
		"reference_ranges": [
			_rr("Homocysteine", nmin=None, nmax=15,
				display="Normal: <15 | Moderate: 15–30 | Severe: >100"),
		],
	},

	{
		"test_name": "Magnesium",
		"test_code": "MG",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Colorimetric (Calmagite)",
		"tat_hours": 4,
		"cost": 250,
		"report_format": "Standard",
		"parameters": [_p("Serum Magnesium", "MG", "mg/dL", order=1, decimals=2)],
		"reference_ranges": [
			_rr("Serum Magnesium", nmin=1.7, nmax=2.3, cmin=1.0, cmax=4.0, display="1.7–2.3"),
		],
	},

	{
		"test_name": "GTT — Glucose Tolerance Test (75g)",
		"test_code": "GTT",
		"department": "Biochemistry",
		"sample_type": "Plasma (Fluoride)",
		"method": "Glucose Oxidase",
		"tat_hours": 4,
		"cost": 250,
		"methodology_note": "Overnight fast. 75g glucose in 250mL water. Collect fasting, 1h and 2h samples.",
		"report_format": "Standard",
		"parameters": [
			_p("Fasting Blood Glucose", "GTT_F", "mg/dL", order=1, bold=1, decimals=0),
			_p("1-Hour Glucose", "GTT_1H", "mg/dL", order=2, decimals=0),
			_p("2-Hour Glucose", "GTT_2H", "mg/dL", order=3, bold=1, decimals=0),
		],
		"reference_ranges": [
			_rr("Fasting Blood Glucose", nmin=70, nmax=100, cmin=40, cmax=300, display="Normal: <100"),
			_rr("2-Hour Glucose", nmin=None, nmax=140,
				display="Normal: <140 | Pre-diabetic: 140–199 | Diabetic: ≥200"),
		],
	},

	{
		"test_name": "Urine Microalbumin (ACR)",
		"test_code": "MICROALB",
		"department": "Clinical Pathology",
		"sample_type": "Urine (First Morning)",
		"method": "Immunoturbidimetry",
		"tat_hours": 6,
		"cost": 400,
		"report_format": "Standard",
		"parameters": [
			_p("Urine Microalbumin", "MICROALB", "mg/L", order=1, bold=1, decimals=1),
			_p("Urine Creatinine", "UR_CREAT", "mg/dL", order=2, decimals=1),
			_p("Albumin/Creatinine Ratio", "ACR", "mg/g", order=3, decimals=1,
			   calc=1, formula="MICROALB / UR_CREAT * 100"),
		],
		"reference_ranges": [
			_rr("Albumin/Creatinine Ratio", nmin=None, nmax=30,
				display="Normal: <30 | Microalbuminuria: 30–300 | Macroalbuminuria: >300"),
		],
	},

	# =====================================================================
	# CLINICAL PATHOLOGY
	# =====================================================================
	{
		"test_name": "Urine Routine & Microscopy",
		"test_code": "URME",
		"department": "Clinical Pathology",
		"sample_type": "Urine (Random)",
		"method": "Dipstick + Microscopy",
		"tat_hours": 4,
		"cost": 150,
		"report_format": "Microscopy",
		"parameters": [
			_p("Colour", "UR_COL", rtype="Multiple Choice", order=1, heading="Physical",
			   options="Pale Yellow\nYellow\nAmber\nOrange\nBrown\nRed\nGreen"),
			_p("Appearance", "UR_APP", rtype="Multiple Choice", order=2, heading="Physical",
			   options="Clear\nSlight Haze\nHazy\nTurbid"),
			_p("pH", "UR_PH", order=3, heading="Chemical", decimals=1),
			_p("Specific Gravity", "UR_SG", order=4, heading="Chemical", decimals=3),
			_p("Protein", "UR_PROT", rtype="Multiple Choice", order=5, heading="Chemical",
			   options="Nil\nTrace\n1+\n2+\n3+\n4+"),
			_p("Glucose", "UR_GLU", rtype="Multiple Choice", order=6, heading="Chemical",
			   options="Nil\nTrace\n1+\n2+\n3+\n4+"),
			_p("Ketone Bodies", "UR_KET", rtype="Multiple Choice", order=7, heading="Chemical",
			   options="Absent\nTrace\n1+\n2+\n3+"),
			_p("Blood", "UR_BLOOD", rtype="Multiple Choice", order=8, heading="Chemical",
			   options="Absent\nTrace\n1+\n2+\n3+"),
			_p("Bilirubin", "UR_BIL", rtype="Multiple Choice", order=9, heading="Chemical",
			   options="Absent\n1+\n2+\n3+"),
			_p("Urobilinogen", "UR_URO", rtype="Multiple Choice", order=10, heading="Chemical",
			   options="Normal\nAbnormal\n1+\n2+\n3+"),
			_p("Nitrite", "UR_NIT", rtype="Positive-Negative", order=11, heading="Chemical"),
			_p("Leucocyte Esterase", "UR_LE", rtype="Multiple Choice", order=12, heading="Chemical",
			   options="Negative\nTrace\n1+\n2+\n3+"),
			_p("Pus Cells (WBC)", "UR_PUS", rtype="Text", order=13, heading="Microscopy"),
			_p("RBC", "UR_RBC", rtype="Text", order=14, heading="Microscopy"),
			_p("Epithelial Cells", "UR_EPI", rtype="Text", order=15, heading="Microscopy"),
			_p("Casts", "UR_CAST", rtype="Text", order=16, heading="Microscopy"),
			_p("Crystals", "UR_CRYS", rtype="Text", order=17, heading="Microscopy"),
			_p("Bacteria", "UR_BACT", rtype="Multiple Choice", order=18, heading="Microscopy",
			   options="None\nFew\nModerate\nMany"),
		],
		"reference_ranges": [
			_rr("Colour",      normal_text="Yellow"),
			_rr("Appearance",  normal_text="Clear"),
			_rr("pH",          nmin=4.5, nmax=8.5, display="4.5–8.5"),
			_rr("Specific Gravity", nmin=1.003, nmax=1.030, display="1.003–1.030"),
			_rr("Protein",     normal_text="Nil"),
			_rr("Glucose",     normal_text="Nil"),
			_rr("Ketone Bodies", normal_text="Absent"),
			_rr("Nitrite",     normal_text="Negative"),
			_rr("Pus Cells (WBC)", normal_text="0–5 /HPF"),
			_rr("RBC",         normal_text="0–2 /HPF"),
			_rr("Casts",       normal_text="Absent / Occasional hyaline"),
		],
	},

	{
		"test_name": "Semen Analysis",
		"test_code": "SEMEN",
		"department": "Clinical Pathology",
		"sample_type": "Semen",
		"method": "Manual + Automated (CASA)",
		"tat_hours": 4,
		"cost": 600,
		"report_format": "Microscopy",
		"parameters": [
			_p("Volume", "SEM_VOL", "mL", order=1, heading="Physical", decimals=1),
			_p("Colour", "SEM_COL", rtype="Multiple Choice", order=2, heading="Physical",
			   options="Opalescent White\nYellow\nClear"),
			_p("Viscosity", "SEM_VIS", rtype="Multiple Choice", order=3, heading="Physical",
			   options="Normal\nIncreased\nDecreased"),
			_p("Liquefaction", "SEM_LIQ", rtype="Multiple Choice", order=4, heading="Physical",
			   options="Complete (<60 min)\nIncomplete"),
			_p("pH", "SEM_PH", order=5, heading="Physical", decimals=1),
			_p("Sperm Count", "SEM_CNT", "millions/mL", order=6, heading="Count & Motility", bold=1, decimals=0),
			_p("Total Sperm Count", "SEM_TCNT", "millions", order=7, heading="Count & Motility",
			   decimals=0, calc=1, formula="SEM_CNT * SEM_VOL"),
			_p("Progressive Motility (PR)", "SEM_PR", "%", order=8, heading="Count & Motility", decimals=1),
			_p("Non-Progressive (NP)", "SEM_NP", "%", order=9, heading="Count & Motility", decimals=1),
			_p("Immotile", "SEM_IM", "%", order=10, heading="Count & Motility", decimals=1),
			_p("Normal Morphology (Kruger)", "SEM_MORPH", "%", order=11, heading="Morphology", decimals=1),
			_p("Pus Cells", "SEM_PUS", rtype="Text", order=12, heading="Others"),
		],
		"reference_ranges": [
			_rr("Volume",        nmin=1.5, nmax=None, display="≥1.5 mL"),
			_rr("pH",            nmin=7.2, nmax=8.0, display="7.2–8.0"),
			_rr("Sperm Count",   nmin=16, nmax=None, display="≥16 million/mL"),
			_rr("Progressive Motility (PR)", nmin=30, nmax=None, display="≥30%"),
			_rr("Normal Morphology (Kruger)", nmin=4, nmax=None, display="≥4%"),
		],
	},

	{
		"test_name": "Stool Routine & Microscopy",
		"test_code": "STOOL",
		"department": "Clinical Pathology",
		"sample_type": "Stool",
		"method": "Gross + Microscopy",
		"tat_hours": 6,
		"cost": 150,
		"report_format": "Microscopy",
		"parameters": [
			_p("Colour", "ST_COL", rtype="Multiple Choice", order=1,
			   options="Brown\nYellow\nGreen\nBlack\nRed\nClay"),
			_p("Consistency", "ST_CON", rtype="Multiple Choice", order=2,
			   options="Formed\nSemi-formed\nLoose\nWatery"),
			_p("Mucus", "ST_MUC", rtype="Positive-Negative", order=3),
			_p("Blood", "ST_BL", rtype="Positive-Negative", order=4),
			_p("Parasites", "ST_PAR", rtype="Text", order=5),
			_p("Ova", "ST_OVA", rtype="Text", order=6),
			_p("Pus Cells", "ST_PUS", rtype="Text", order=7),
			_p("Fat Globules", "ST_FAT", rtype="Multiple Choice", order=8,
			   options="None\nFew\nModerate\nMany"),
		],
		"reference_ranges": [
			_rr("Mucus",     normal_text="Absent"),
			_rr("Blood",     normal_text="Absent"),
			_rr("Parasites", normal_text="Nil seen"),
			_rr("Ova",       normal_text="Nil seen"),
		],
	},

	{
		"test_name": "Occult Blood (Stool)",
		"test_code": "OCCBLOOD",
		"department": "Clinical Pathology",
		"sample_type": "Stool",
		"method": "Immunochromatographic (Guaiac / Immunochemical)",
		"tat_hours": 4,
		"cost": 200,
		"report_format": "Standard",
		"parameters": [_p("Occult Blood", "OCCBLOOD", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("Occult Blood", normal_text="Negative")],
	},

	# =====================================================================
	# SEROLOGY & IMMUNOLOGY
	# =====================================================================
	{
		"test_name": "Viral Markers (HBsAg + HCV + HIV + VDRL)",
		"test_code": "VIRAL4",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "Rapid ICT / ELISA",
		"tat_hours": 6,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [
			_p("HBsAg", "HBSAG", rtype="Positive-Negative", order=1, bold=1),
			_p("HCV (Anti-Hepatitis C)", "HCV", rtype="Positive-Negative", order=2, bold=1),
			_p("HIV I & II", "HIV", rtype="Positive-Negative", order=3, bold=1),
			_p("VDRL (Syphilis)", "VDRL", rtype="Positive-Negative", order=4),
		],
		"reference_ranges": [
			_rr("HBsAg", normal_text="Non-Reactive"),
			_rr("HCV (Anti-Hepatitis C)", normal_text="Non-Reactive"),
			_rr("HIV I & II", normal_text="Non-Reactive"),
			_rr("VDRL (Syphilis)", normal_text="Non-Reactive"),
		],
	},

	{
		"test_name": "HBsAg (Hepatitis B Surface Antigen)",
		"test_code": "HBSAG",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 4,
		"cost": 250,
		"report_format": "Standard",
		"parameters": [_p("HBsAg", "HBSAG", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("HBsAg", normal_text="Non-Reactive")],
	},

	{
		"test_name": "Dengue (NS1 + IgM + IgG)",
		"test_code": "DENGUE",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "Rapid ICT / ELISA",
		"tat_hours": 4,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [
			_p("Dengue NS1 Antigen", "DENG_NS1", rtype="Positive-Negative", order=1, bold=1),
			_p("Dengue IgM", "DENG_IGM", rtype="Positive-Negative", order=2),
			_p("Dengue IgG", "DENG_IGG", rtype="Positive-Negative", order=3),
			_p("Interpretation", "DENG_INTERP", rtype="Text", order=4, bold=1),
		],
		"reference_ranges": [
			_rr("Dengue NS1 Antigen", normal_text="Negative"),
			_rr("Dengue IgM", normal_text="Negative"),
			_rr("Dengue IgG", normal_text="Negative"),
		],
	},

	{
		"test_name": "Malaria Antigen (Rapid)",
		"test_code": "MALARIA",
		"department": "Serology & Immunology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Rapid ICT",
		"tat_hours": 1,
		"cost": 300,
		"report_format": "Standard",
		"parameters": [
			_p("P. falciparum", "MAL_PF", rtype="Positive-Negative", order=1, bold=1),
			_p("P. vivax", "MAL_PV", rtype="Positive-Negative", order=2, bold=1),
		],
		"reference_ranges": [
			_rr("P. falciparum", normal_text="Negative"),
			_rr("P. vivax", normal_text="Negative"),
		],
	},

	{
		"test_name": "Typhoid IgM (Widal / Typhidot)",
		"test_code": "TYPHOID",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "Typhidot Rapid ICT / Widal",
		"tat_hours": 4,
		"cost": 350,
		"report_format": "Standard",
		"parameters": [
			_p("S. typhi O", "WIDAL_O", rtype="Text", order=1),
			_p("S. typhi H", "WIDAL_H", rtype="Text", order=2),
			_p("S. paratyphi AO", "WIDAL_AO", rtype="Text", order=3),
			_p("S. paratyphi BH", "WIDAL_BH", rtype="Text", order=4),
			_p("Interpretation", "WIDAL_INTERP", rtype="Text", order=5, bold=1),
		],
		"reference_ranges": [
			_rr("S. typhi O", normal_text="Titre <1:80"),
			_rr("S. typhi H", normal_text="Titre <1:80"),
		],
	},

	{
		"test_name": "RA Factor Quantitative",
		"test_code": "RAF",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "Latex Agglutination / Nephelometry",
		"tat_hours": 6,
		"cost": 350,
		"report_format": "Standard",
		"parameters": [_p("RA Factor", "RAF", "IU/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [_rr("RA Factor", nmin=None, nmax=20, display="<20 (Negative)")],
	},

	{
		"test_name": "ASO Titer (Antistreptolysin O)",
		"test_code": "ASO",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "Latex Agglutination / Nephelometry",
		"tat_hours": 6,
		"cost": 350,
		"report_format": "Standard",
		"parameters": [_p("ASO Titer", "ASO", "IU/mL", order=1, bold=1, decimals=0)],
		"reference_ranges": [_rr("ASO Titer", nmin=None, nmax=200, display="<200 IU/mL")],
	},

	{
		"test_name": "ANA (Antinuclear Antibody) by ELISA",
		"test_code": "ANA",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / IIF",
		"tat_hours": 24,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [
			_p("ANA", "ANA", rtype="Positive-Negative", order=1, bold=1),
			_p("ANA Titer", "ANA_TITER", rtype="Text", order=2),
			_p("Pattern", "ANA_PAT", rtype="Text", order=3),
		],
		"reference_ranges": [_rr("ANA", normal_text="Negative")],
	},

	{
		"test_name": "Anti-CCP (Anti-Cyclic Citrullinated Peptide)",
		"test_code": "ANTICCP",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("Anti-CCP", "ANTICCP", "U/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Anti-CCP", nmin=None, nmax=20,
				display="Negative: <20 | Weakly positive: 20–39 | Positive: ≥40"),
		],
	},

	{
		"test_name": "Beta-hCG Quantitative",
		"test_code": "BHCG",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 6,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Beta-hCG", "BHCG", "mIU/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("Beta-hCG", "Female", nmin=None, nmax=5.0,
				display="Non-pregnant: <5.0 | Pregnancy: >25"),
			_rr("Beta-hCG", "Male", nmin=None, nmax=5.0, display="<5.0"),
		],
	},

	{
		"test_name": "Chikungunya IgM",
		"test_code": "CHIKV",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / Rapid ICT",
		"tat_hours": 6,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Chikungunya IgM", "CHIKV", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("Chikungunya IgM", normal_text="Negative")],
	},

	{
		"test_name": "IgE Total",
		"test_code": "IGE",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / FEIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Total IgE", "IGE", "IU/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [_rr("Total IgE", nmin=None, nmax=100, display="Normal: <100 IU/mL")],
	},

	# =====================================================================
	# MICROBIOLOGY
	# =====================================================================
	{
		"test_name": "Urine Culture & Sensitivity",
		"test_code": "URINECS",
		"department": "Microbiology",
		"sample_type": "Urine (First Morning)",
		"method": "Aerobic Culture on CLED / Blood Agar + Kirby-Bauer Disk Diffusion",
		"tat_hours": 48,
		"cost": 500,
		"report_format": "Culture",
		"parameters": _abx_urine(),
		"reference_ranges": [_rr("Organism", normal_text="No growth / Commensal organisms")],
	},

	{
		"test_name": "Blood Culture & Sensitivity",
		"test_code": "BLOODCS",
		"department": "Microbiology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Automated Blood Culture (BacT/ALERT / BACTEC) + Kirby-Bauer",
		"tat_hours": 72,
		"cost": 1200,
		"report_format": "Culture",
		"parameters": _abx_blood(),
		"reference_ranges": [_rr("Organism", normal_text="No growth (after 5 days)")],
	},

	{
		"test_name": "Pus / Wound Culture & Sensitivity",
		"test_code": "PUSCS",
		"department": "Microbiology",
		"sample_type": "Swab",
		"method": "Aerobic + Anaerobic Culture + Kirby-Bauer",
		"tat_hours": 48,
		"cost": 600,
		"report_format": "Culture",
		"parameters": _abx_urine(),
		"reference_ranges": [_rr("Organism", normal_text="No growth")],
	},

	{
		"test_name": "Sputum Culture & Sensitivity",
		"test_code": "SPUTCS",
		"department": "Microbiology",
		"sample_type": "Sputum",
		"method": "Aerobic Culture on Blood/Chocolate Agar + Kirby-Bauer",
		"tat_hours": 48,
		"cost": 600,
		"report_format": "Culture",
		"parameters": _abx_sputum(),
		"reference_ranges": [_rr("Organism", normal_text="Normal respiratory flora")],
	},

	{
		"test_name": "AFB Smear — Acid Fast Bacilli",
		"test_code": "AFB",
		"department": "Microbiology",
		"sample_type": "Sputum",
		"method": "Ziehl-Neelsen (ZN) Staining",
		"tat_hours": 6,
		"cost": 250,
		"report_format": "Microscopy",
		"parameters": [
			_p("AFB Smear Result", "AFB", rtype="Multiple Choice", order=1, bold=1,
			   options="No AFB seen (Negative)\n1-9 AFB/100 HPF (Scanty)\n10-99 AFB/100 HPF (1+)\n1-10 AFB/HPF (2+)\n>10 AFB/HPF (3+)"),
		],
		"reference_ranges": [_rr("AFB Smear Result", normal_text="No AFB seen (Negative)")],
	},

	{
		"test_name": "Throat Swab Culture & Sensitivity",
		"test_code": "THROATCS",
		"department": "Microbiology",
		"sample_type": "Swab",
		"method": "Aerobic Culture on Blood Agar + Kirby-Bauer",
		"tat_hours": 48,
		"cost": 500,
		"report_format": "Culture",
		"parameters": _abx_urine(),
		"reference_ranges": [_rr("Organism", normal_text="Normal oral flora")],
	},

	# =====================================================================
	# ENDOCRINOLOGY
	# =====================================================================
	{
		"test_name": "Thyroid Function Test (T3 / T4 / TSH)",
		"test_code": "TFT",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 450,
		"report_format": "Standard",
		"parameters": [
			_p("T3 (Triiodothyronine)", "T3", "ng/dL", order=1, decimals=2),
			_p("T4 (Thyroxine)", "T4", "µg/dL", order=2, decimals=2),
			_p("TSH", "TSH", "µIU/mL", order=3, bold=1, decimals=3),
		],
		"reference_ranges": [
			_rr("T3 (Triiodothyronine)", nmin=60, nmax=200, display="60–200"),
			_rr("T4 (Thyroxine)", nmin=4.5, nmax=12.5, display="4.5–12.5"),
			_rr("TSH", nmin=0.4, nmax=4.0, cmin=0.01, cmax=100,
				display="0.4–4.0 | Hypo: >4.0 | Hyper: <0.4"),
		],
	},

	{
		"test_name": "Free Thyroid Function Test (FT3 / FT4 / TSH)",
		"test_code": "FTFT",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 650,
		"report_format": "Standard",
		"parameters": [
			_p("Free T3 (FT3)", "FT3", "pg/mL", order=1, decimals=2),
			_p("Free T4 (FT4)", "FT4", "ng/dL", order=2, decimals=2),
			_p("TSH", "TSH", "µIU/mL", order=3, bold=1, decimals=3),
		],
		"reference_ranges": [
			_rr("Free T3 (FT3)", nmin=2.3, nmax=4.2, display="2.3–4.2"),
			_rr("Free T4 (FT4)", nmin=0.8, nmax=1.8, display="0.8–1.8"),
			_rr("TSH", nmin=0.4, nmax=4.0, cmin=0.01, cmax=100, display="0.4–4.0"),
		],
	},

	{
		"test_name": "TSH (Thyroid Stimulating Hormone)",
		"test_code": "TSH",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 6,
		"cost": 250,
		"report_format": "Standard",
		"parameters": [_p("TSH", "TSH", "µIU/mL", order=1, bold=1, decimals=3)],
		"reference_ranges": [
			_rr("TSH", nmin=0.4, nmax=4.0, cmin=0.01, cmax=100, display="0.4–4.0"),
		],
	},

	{
		"test_name": "Anti-TPO (Anti-Thyroid Peroxidase)",
		"test_code": "ANTITPO",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Anti-TPO", "ANTITPO", "IU/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Anti-TPO", nmin=None, nmax=34, display="Negative: <34 | Positive: ≥34"),
		],
	},

	{
		"test_name": "Prolactin",
		"test_code": "PRL",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 500,
		"report_format": "Standard",
		"parameters": [_p("Prolactin", "PRL", "ng/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("Prolactin", "Male",   nmin=4.0, nmax=15.2, display="4.0–15.2"),
			_rr("Prolactin", "Female", nmin=4.8, nmax=23.3, display="4.8–23.3 (Non-pregnant)"),
		],
	},

	{
		"test_name": "FSH (Follicle Stimulating Hormone)",
		"test_code": "FSH",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 500,
		"report_format": "Standard",
		"parameters": [_p("FSH", "FSH", "mIU/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("FSH", "Male",   nmin=1.5, nmax=12.4, display="1.5–12.4"),
			_rr("FSH", "Female", nmin=3.5, nmax=12.5, display="3.5–12.5 (Follicular)"),
		],
	},

	{
		"test_name": "LH (Luteinising Hormone)",
		"test_code": "LH",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 500,
		"report_format": "Standard",
		"parameters": [_p("LH", "LH", "mIU/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("LH", "Male",   nmin=1.7, nmax=8.6, display="1.7–8.6"),
			_rr("LH", "Female", nmin=2.4, nmax=12.6, display="2.4–12.6 (Follicular)"),
		],
	},

	{
		"test_name": "Testosterone Total",
		"test_code": "TESTO",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Testosterone Total", "TESTO", "ng/dL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Testosterone Total", "Male",   nmin=264, nmax=916, display="264–916"),
			_rr("Testosterone Total", "Female", nmin=15,  nmax=70,  display="15–70"),
		],
	},

	{
		"test_name": "Estradiol (E2)",
		"test_code": "E2",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Estradiol (E2)", "E2", "pg/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Estradiol (E2)", "Male",   nmin=10, nmax=40,  display="10–40"),
			_rr("Estradiol (E2)", "Female", nmin=30, nmax=400, display="30–400 (cycle dependent)"),
		],
	},

	{
		"test_name": "Progesterone",
		"test_code": "PROG",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 24,
		"cost": 600,
		"report_format": "Standard",
		"parameters": [_p("Progesterone", "PROG", "ng/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("Progesterone", "Female", nmin=None, nmax=1.5,
				display="Follicular: <1.5 | Ovulatory: 3–5 | Luteal: 11.2–90"),
		],
	},

	{
		"test_name": "DHEA-S",
		"test_code": "DHEAS",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("DHEA-S", "DHEAS", "µg/dL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("DHEA-S", "Male",   nmin=80,  nmax=560, display="80–560"),
			_rr("DHEA-S", "Female", nmin=35,  nmax=430, display="35–430"),
		],
	},

	{
		"test_name": "Insulin Fasting",
		"test_code": "INSULIN",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Insulin Fasting", "INSULIN", "µIU/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [_rr("Insulin Fasting", nmin=2.6, nmax=24.9, display="2.6–24.9")],
	},

	{
		"test_name": "Cortisol (Morning)",
		"test_code": "CORT",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Cortisol (8 AM)", "CORT", "µg/dL", order=1, bold=1, decimals=1)],
		"reference_ranges": [_rr("Cortisol (8 AM)", nmin=6.2, nmax=19.4, display="AM: 6.2–19.4")],
	},

	# =====================================================================
	# TUMOR MARKERS
	# =====================================================================
	{
		"test_name": "PSA Total (Prostate Specific Antigen)",
		"test_code": "PSA",
		"department": "Tumor Markers",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("PSA Total", "PSA", "ng/mL", order=1, bold=1, decimals=3)],
		"reference_ranges": [
			_rr("PSA Total", nmin=None, nmax=4.0,
				display="Normal: <4.0 | Borderline: 4–10 | High: >10"),
		],
	},

	{
		"test_name": "AFP (Alpha Fetoprotein)",
		"test_code": "AFP",
		"department": "Tumor Markers",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("AFP", "AFP", "ng/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [_rr("AFP", nmin=None, nmax=10, display="<10 ng/mL")],
	},

	{
		"test_name": "CEA (Carcinoembryonic Antigen)",
		"test_code": "CEA",
		"department": "Tumor Markers",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [_p("CEA", "CEA", "ng/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("CEA", nmin=None, nmax=5.0, display="Non-smokers: <3.0 | Smokers: <5.0"),
		],
	},

	{
		"test_name": "CA-125",
		"test_code": "CA125",
		"department": "Tumor Markers",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 1000,
		"report_format": "Standard",
		"parameters": [_p("CA-125", "CA125", "U/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [_rr("CA-125", nmin=None, nmax=35, display="<35 U/mL")],
	},

	{
		"test_name": "CA 19-9",
		"test_code": "CA199",
		"department": "Tumor Markers",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("CA 19-9", "CA199", "U/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [_rr("CA 19-9", nmin=None, nmax=37, display="<37 U/mL")],
	},

	{
		"test_name": "CA 15-3",
		"test_code": "CA153",
		"department": "Tumor Markers",
		"sample_type": "Serum (Plain)",
		"method": "CMIA / ECLIA",
		"tat_hours": 24,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("CA 15-3", "CA153", "U/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [_rr("CA 15-3", nmin=None, nmax=30, display="<30 U/mL")],
	},

	# =====================================================================
	# VIROLOGY & MOLECULAR (Outsourced)
	# =====================================================================
	{
		"test_name": "HBV DNA Quantitative (PCR)",
		"test_code": "HBVDNA",
		"department": "Virology & Molecular",
		"sample_type": "Serum (Plain)",
		"method": "Real-time PCR",
		"tat_hours": 72,
		"cost": 3500,
		"is_outsourced": 1,
		"report_format": "Standard",
		"parameters": [
			_p("HBV DNA", "HBVDNA", "IU/mL", order=1, bold=1, decimals=0),
			_p("Log Value", "HBV_LOG", "log10 IU/mL", order=2, decimals=2),
			_p("Interpretation", "HBV_INTERP", rtype="Text", order=3, bold=1),
		],
		"reference_ranges": [_rr("HBV DNA", nmin=None, nmax=20, display="Not Detected: <20 IU/mL")],
	},

	{
		"test_name": "HCV RNA Quantitative (PCR)",
		"test_code": "HCVRNA",
		"department": "Virology & Molecular",
		"sample_type": "Serum (Plain)",
		"method": "Real-time PCR",
		"tat_hours": 72,
		"cost": 3800,
		"is_outsourced": 1,
		"report_format": "Standard",
		"parameters": [
			_p("HCV RNA", "HCVRNA", "IU/mL", order=1, bold=1, decimals=0),
			_p("Log Value", "HCV_LOG", "log10 IU/mL", order=2, decimals=2),
			_p("Interpretation", "HCV_INTERP", rtype="Text", order=3, bold=1),
		],
		"reference_ranges": [_rr("HCV RNA", nmin=None, nmax=15, display="Not Detected: <15 IU/mL")],
	},

	{
		"test_name": "COVID-19 RT-PCR",
		"test_code": "COVID19",
		"department": "Virology & Molecular",
		"sample_type": "Swab",
		"method": "Reverse Transcription PCR (RT-PCR)",
		"tat_hours": 24,
		"cost": 500,
		"is_outsourced": 1,
		"report_format": "Standard",
		"parameters": [
			_p("SARS-CoV-2 RNA (E gene)", "COVID_E", rtype="Positive-Negative", order=1, bold=1),
			_p("SARS-CoV-2 RNA (ORF1ab)", "COVID_ORF", rtype="Positive-Negative", order=2),
			_p("Ct Value", "COVID_CT", order=3, decimals=1),
			_p("Interpretation", "COVID_INTERP", rtype="Text", order=4, bold=1),
		],
		"reference_ranges": [_rr("SARS-CoV-2 RNA (E gene)", normal_text="Negative")],
	},

	{
		"test_name": "Dengue PCR (RT-PCR)",
		"test_code": "DENGPCR",
		"department": "Virology & Molecular",
		"sample_type": "Serum (Plain)",
		"method": "Real-time RT-PCR",
		"tat_hours": 48,
		"cost": 2500,
		"is_outsourced": 1,
		"report_format": "Standard",
		"parameters": [
			_p("Dengue Virus RNA", "DENGPCR", rtype="Positive-Negative", order=1, bold=1),
			_p("Serotype", "DENG_TYPE", rtype="Text", order=2),
		],
		"reference_ranges": [_rr("Dengue Virus RNA", normal_text="Not Detected")],
	},

	# =====================================================================
	# ADDITIONAL HAEMATOLOGY TESTS
	# =====================================================================
	{
		"test_name": "Bleeding Time (BT)",
		"test_code": "BT",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Duke Method / Ivy Method",
		"tat_hours": 1,
		"cost": 150,
		"report_format": "Standard",
		"parameters": [_p("Bleeding Time", "BT", "minutes", order=1, decimals=1)],
		"reference_ranges": [_rr("Bleeding Time", nmin=1, nmax=6, display="1–6 minutes")],
	},

	{
		"test_name": "Clotting Time (CT)",
		"test_code": "CT",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Capillary Tube Method",
		"tat_hours": 1,
		"cost": 150,
		"report_format": "Standard",
		"parameters": [_p("Clotting Time", "CT", "minutes", order=1, decimals=1)],
		"reference_ranges": [_rr("Clotting Time", nmin=4, nmax=10, display="4–10 minutes")],
	},

	{
		"test_name": "Sickling Test",
		"test_code": "SICKLE",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Sodium Metabisulfite Reduction Test",
		"tat_hours": 4,
		"cost": 200,
		"report_format": "Standard",
		"parameters": [_p("Sickling Test", "SICKLE", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("Sickling Test", normal_text="Negative")],
	},

	{
		"test_name": "Hb HPLC (Haemoglobin Electrophoresis)",
		"test_code": "HBHPLC",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "High Performance Liquid Chromatography (HPLC)",
		"tat_hours": 24,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [
			_p("HbA", "HBA", "%", order=1, bold=1, decimals=1),
			_p("HbA2", "HBA2", "%", order=2, decimals=1),
			_p("HbF", "HBF", "%", order=3, decimals=1),
			_p("HbS", "HBS", "%", order=4, decimals=1),
			_p("Other Variants", "HBOTHER", rtype="Text", order=5),
		],
		"reference_ranges": [
			_rr("HbA", nmin=95, nmax=98, display="95–98%"),
			_rr("HbA2", nmin=2.0, nmax=3.5, display="2.0–3.5%"),
			_rr("HbF", nmin=None, nmax=2.0, display="<2.0%"),
			_rr("HbS", nmin=None, nmax=0, display="Absent"),
		],
	},

	{
		"test_name": "Absolute Eosinophil Count (AEC)",
		"test_code": "AEC",
		"department": "Haematology",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Automated / Manual Count",
		"tat_hours": 4,
		"cost": 150,
		"report_format": "Standard",
		"parameters": [_p("Absolute Eosinophil Count", "AEC", "cells/µL", order=1, decimals=0)],
		"reference_ranges": [_rr("Absolute Eosinophil Count", nmin=40, nmax=440, display="40–440")],
	},

	# =====================================================================
	# ADDITIONAL BIOCHEMISTRY TESTS
	# =====================================================================
	{
		"test_name": "Serum Bicarbonate",
		"test_code": "HCO3",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Enzymatic / ISE",
		"tat_hours": 4,
		"cost": 200,
		"report_format": "Standard",
		"parameters": [_p("Serum Bicarbonate", "HCO3", "mEq/L", order=1, decimals=1)],
		"reference_ranges": [_rr("Serum Bicarbonate", nmin=22, nmax=29, display="22–29")],
	},

	{
		"test_name": "LDH (Lactate Dehydrogenase)",
		"test_code": "LDH",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Enzymatic Colorimetric",
		"tat_hours": 4,
		"cost": 350,
		"report_format": "Standard",
		"parameters": [_p("LDH", "LDH", "U/L", order=1, decimals=0)],
		"reference_ranges": [_rr("LDH", nmin=140, nmax=280, display="140–280")],
	},

	{
		"test_name": "Serum Protein Electrophoresis",
		"test_code": "SPE",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Agarose Gel Electrophoresis",
		"tat_hours": 48,
		"cost": 1500,
		"report_format": "Standard",
		"parameters": [
			_p("Total Protein", "SPE_TP", "g/dL", order=1, decimals=1),
			_p("Albumin", "SPE_ALB", "%", order=2, decimals=1),
			_p("Alpha-1 Globulin", "SPE_A1", "%", order=3, decimals=1),
			_p("Alpha-2 Globulin", "SPE_A2", "%", order=4, decimals=1),
			_p("Beta Globulin", "SPE_BETA", "%", order=5, decimals=1),
			_p("Gamma Globulin", "SPE_GAMMA", "%", order=6, decimals=1),
		],
		"reference_ranges": [
			_rr("Albumin", nmin=55, nmax=65, display="55–65%"),
			_rr("Alpha-1 Globulin", nmin=2.5, nmax=5.0, display="2.5–5.0%"),
			_rr("Alpha-2 Globulin", nmin=7.0, nmax=13.0, display="7.0–13.0%"),
			_rr("Beta Globulin", nmin=8.0, nmax=14.0, display="8.0–14.0%"),
			_rr("Gamma Globulin", nmin=11.0, nmax=21.0, display="11.0–21.0%"),
		],
	},

	{
		"test_name": "Serum Phosphorus",
		"test_code": "PHOS",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Colorimetric (Molybdate)",
		"tat_hours": 4,
		"cost": 150,
		"report_format": "Standard",
		"parameters": [_p("Serum Phosphorus", "PHOS", "mg/dL", order=1, decimals=1)],
		"reference_ranges": [_rr("Serum Phosphorus", nmin=2.5, nmax=4.5, display="2.5–4.5")],
	},

	{
		"test_name": "Creatine Kinase (CK Total)",
		"test_code": "CK",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Enzymatic UV",
		"tat_hours": 4,
		"cost": 400,
		"report_format": "Standard",
		"parameters": [_p("Creatine Kinase Total", "CK", "U/L", order=1, decimals=0)],
		"reference_ranges": [
			_rr("Creatine Kinase Total", "Male",   nmin=38, nmax=174, display="38–174"),
			_rr("Creatine Kinase Total", "Female", nmin=26, nmax=140, display="26–140"),
		],
	},

	{
		"test_name": "Zinc",
		"test_code": "ZINC",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Atomic Absorption Spectrophotometry",
		"tat_hours": 48,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("Serum Zinc", "ZINC", "µg/dL", order=1, decimals=1)],
		"reference_ranges": [_rr("Serum Zinc", nmin=70, nmax=120, display="70–120")],
	},

	{
		"test_name": "Copper",
		"test_code": "COPPER",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Atomic Absorption Spectrophotometry",
		"tat_hours": 48,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("Serum Copper", "COPPER", "µg/dL", order=1, decimals=1)],
		"reference_ranges": [
			_rr("Serum Copper", "Male",   nmin=70, nmax=140, display="70–140"),
			_rr("Serum Copper", "Female", nmin=80, nmax=155, display="80–155"),
		],
	},

	{
		"test_name": "NT-proBNP",
		"test_code": "NTPROBNP",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 6,
		"cost": 2500,
		"report_format": "Standard",
		"parameters": [_p("NT-proBNP", "NTPROBNP", "pg/mL", order=1, bold=1, decimals=0)],
		"reference_ranges": [
			_rr("NT-proBNP", nmin=None, nmax=125, display="Normal: <125 | Heart failure likely: >450"),
		],
	},

	{
		"test_name": "BNP (Brain Natriuretic Peptide)",
		"test_code": "BNP",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "CMIA",
		"tat_hours": 6,
		"cost": 2200,
		"report_format": "Standard",
		"parameters": [_p("BNP", "BNP", "pg/mL", order=1, bold=1, decimals=0)],
		"reference_ranges": [
			_rr("BNP", nmin=None, nmax=100, display="Normal: <100 | Heart failure likely: >400"),
		],
	},

	{
		"test_name": "Lipoprotein(a)",
		"test_code": "LPA",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Immunoturbidimetry",
		"tat_hours": 24,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("Lipoprotein(a)", "LPA", "mg/dL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Lipoprotein(a)", nmin=None, nmax=30, display="Desirable: <30 | High risk: >30"),
		],
	},

	{
		"test_name": "Apolipoprotein A1",
		"test_code": "APOA1",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Immunoturbidimetry",
		"tat_hours": 24,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [_p("Apolipoprotein A1", "APOA1", "mg/dL", order=1, decimals=0)],
		"reference_ranges": [
			_rr("Apolipoprotein A1", "Male",   nmin=120, nmax=160, display="120–160"),
			_rr("Apolipoprotein A1", "Female", nmin=140, nmax=180, display="140–180"),
		],
	},

	{
		"test_name": "Apolipoprotein B",
		"test_code": "APOB",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Immunoturbidimetry",
		"tat_hours": 24,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [_p("Apolipoprotein B", "APOB", "mg/dL", order=1, decimals=0)],
		"reference_ranges": [
			_rr("Apolipoprotein B", nmin=None, nmax=100, display="Desirable: <100"),
		],
	},

	{
		"test_name": "Fibrinogen",
		"test_code": "FIBRIN",
		"department": "Haematology",
		"sample_type": "Plasma (Citrate)",
		"method": "Clauss Method",
		"tat_hours": 4,
		"cost": 600,
		"report_format": "Standard",
		"parameters": [_p("Fibrinogen", "FIBRIN", "mg/dL", order=1, decimals=0)],
		"reference_ranges": [_rr("Fibrinogen", nmin=200, nmax=400, display="200–400")],
	},

	# =====================================================================
	# ADDITIONAL ENDOCRINOLOGY TESTS
	# =====================================================================
	{
		"test_name": "Anti-Thyroglobulin (Anti-TG)",
		"test_code": "ANTITG",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA / CMIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Anti-Thyroglobulin", "ANTITG", "IU/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Anti-Thyroglobulin", nmin=None, nmax=115, display="Negative: <115 | Positive: ≥115"),
		],
	},

	{
		"test_name": "ACTH (Adrenocorticotropic Hormone)",
		"test_code": "ACTH",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 48,
		"cost": 1500,
		"report_format": "Standard",
		"parameters": [_p("ACTH", "ACTH", "pg/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [_rr("ACTH", nmin=7.2, nmax=63.3, display="7.2–63.3 (8 AM sample)")],
	},

	{
		"test_name": "IGF-1 (Insulin-like Growth Factor 1)",
		"test_code": "IGF1",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "CMIA",
		"tat_hours": 48,
		"cost": 1800,
		"report_format": "Standard",
		"parameters": [_p("IGF-1", "IGF1", "ng/mL", order=1, bold=1, decimals=0)],
		"reference_ranges": [
			_rr("IGF-1", nmin=115, nmax=307, display="115–307 (age 20-30 years, varies by age)"),
		],
	},

	{
		"test_name": "Free Testosterone",
		"test_code": "FREETESTO",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 24,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("Free Testosterone", "FREETESTO", "pg/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Free Testosterone", "Male",   nmin=9.0, nmax=30.0, display="9.0–30.0"),
			_rr("Free Testosterone", "Female", nmin=0.3, nmax=1.9,  display="0.3–1.9"),
		],
	},

	{
		"test_name": "17-OH Progesterone",
		"test_code": "OHP17",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 48,
		"cost": 1500,
		"report_format": "Standard",
		"parameters": [_p("17-OH Progesterone", "OHP17", "ng/mL", order=1, bold=1, decimals=2)],
		"reference_ranges": [
			_rr("17-OH Progesterone", "Male",   nmin=0.2, nmax=1.8, display="0.2–1.8"),
			_rr("17-OH Progesterone", "Female", nmin=0.2, nmax=2.8, display="0.2–2.8 (Follicular)"),
		],
	},

	# =====================================================================
	# ADDITIONAL SEROLOGY TESTS
	# =====================================================================
	{
		"test_name": "HBeAg (Hepatitis B e Antigen)",
		"test_code": "HBEAG",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 600,
		"report_format": "Standard",
		"parameters": [_p("HBeAg", "HBEAG", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("HBeAg", normal_text="Non-Reactive")],
	},

	{
		"test_name": "Anti-HBs (Hepatitis B Surface Antibody)",
		"test_code": "ANTIHBS",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 500,
		"report_format": "Standard",
		"parameters": [
			_p("Anti-HBs", "ANTIHBS", "mIU/mL", order=1, bold=1, decimals=1),
			_p("Interpretation", "ANTIHBS_INTERP", rtype="Multiple Choice", order=2,
			   options="Non-Immune (<10)\nImmune (≥10)"),
		],
		"reference_ranges": [
			_rr("Anti-HBs", nmin=10, nmax=None, display="Immune: ≥10 mIU/mL | Non-immune: <10"),
		],
	},

	{
		"test_name": "TPHA (Treponema pallidum Haemagglutination)",
		"test_code": "TPHA",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "Passive Haemagglutination",
		"tat_hours": 6,
		"cost": 400,
		"report_format": "Standard",
		"parameters": [_p("TPHA", "TPHA", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("TPHA", normal_text="Non-Reactive")],
	},

	{
		"test_name": "Anti-dsDNA (Anti-Double Stranded DNA)",
		"test_code": "ANTIDSDNA",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / IIF",
		"tat_hours": 24,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("Anti-dsDNA", "ANTIDSDNA", "IU/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Anti-dsDNA", nmin=None, nmax=30, display="Negative: <30 | Positive: ≥30"),
		],
	},

	{
		"test_name": "CMV IgM (Cytomegalovirus IgM)",
		"test_code": "CMVIGM",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("CMV IgM", "CMVIGM", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("CMV IgM", normal_text="Negative")],
	},

	{
		"test_name": "CMV IgG (Cytomegalovirus IgG)",
		"test_code": "CMVIGG",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("CMV IgG", "CMVIGG", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("CMV IgG", normal_text="Negative (Non-immune)")],
	},

	{
		"test_name": "Rubella IgM",
		"test_code": "RUBELLAIGM",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Rubella IgM", "RUBELLAIGM", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("Rubella IgM", normal_text="Negative")],
	},

	{
		"test_name": "Rubella IgG",
		"test_code": "RUBELLAIGG",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 700,
		"report_format": "Standard",
		"parameters": [_p("Rubella IgG", "RUBELLAIGG", "IU/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Rubella IgG", nmin=10, nmax=None, display="Immune: ≥10 IU/mL | Non-immune: <10"),
		],
	},

	{
		"test_name": "Toxoplasma IgM",
		"test_code": "TOXOIGM",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("Toxoplasma IgM", "TOXOIGM", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("Toxoplasma IgM", normal_text="Negative")],
	},

	{
		"test_name": "Toxoplasma IgG",
		"test_code": "TOXOIGG",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("Toxoplasma IgG", "TOXOIGG", "IU/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Toxoplasma IgG", nmin=None, nmax=3, display="Negative: <3 | Positive: ≥3"),
		],
	},

	{
		"test_name": "EBV VCA IgM (Epstein-Barr Virus)",
		"test_code": "EBVIGM",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [_p("EBV VCA IgM", "EBVIGM", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("EBV VCA IgM", normal_text="Negative")],
	},

	{
		"test_name": "EBV VCA IgG",
		"test_code": "EBVIGG",
		"department": "Serology & Immunology",
		"sample_type": "Serum (Plain)",
		"method": "ELISA / CMIA",
		"tat_hours": 24,
		"cost": 900,
		"report_format": "Standard",
		"parameters": [_p("EBV VCA IgG", "EBVIGG", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("EBV VCA IgG", normal_text="Negative (Non-immune)")],
	},

	# =====================================================================
	# ADDITIONAL CLINICAL PATHOLOGY TESTS
	# =====================================================================
	{
		"test_name": "CSF Routine & Microscopy",
		"test_code": "CSF",
		"department": "Clinical Pathology",
		"sample_type": "Swab",
		"method": "Gross + Microscopy + Biochemistry",
		"tat_hours": 4,
		"cost": 600,
		"report_format": "Microscopy",
		"parameters": [
			_p("Appearance", "CSF_APP", rtype="Multiple Choice", order=1, heading="Physical",
			   options="Clear\nTurbid\nBloody\nXanthochromic"),
			_p("Total Cell Count", "CSF_TCC", "cells/µL", order=2, heading="Cell Count", decimals=0),
			_p("Polymorphs", "CSF_POLY", "%", order=3, heading="Cell Count", decimals=0),
			_p("Lymphocytes", "CSF_LYMPH", "%", order=4, heading="Cell Count", decimals=0),
			_p("Protein", "CSF_PROT", "mg/dL", order=5, heading="Biochemistry", decimals=1),
			_p("Glucose", "CSF_GLU", "mg/dL", order=6, heading="Biochemistry", decimals=0),
			_p("Chloride", "CSF_CL", "mEq/L", order=7, heading="Biochemistry", decimals=1),
			_p("Gram Stain", "CSF_GRAM", rtype="Text", order=8, heading="Microscopy"),
			_p("AFB Stain", "CSF_AFB", rtype="Text", order=9, heading="Microscopy"),
		],
		"reference_ranges": [
			_rr("Appearance", normal_text="Clear and colorless"),
			_rr("Total Cell Count", nmin=0, nmax=5, display="0–5 cells/µL"),
			_rr("Protein", nmin=15, nmax=45, display="15–45 mg/dL"),
			_rr("Glucose", nmin=50, nmax=80, display="50–80 mg/dL (2/3 of blood glucose)"),
			_rr("Chloride", nmin=118, nmax=132, display="118–132 mEq/L"),
		],
	},

	{
		"test_name": "24-Hour Urine Protein",
		"test_code": "24HURPROT",
		"department": "Clinical Pathology",
		"sample_type": "Urine (First Morning)",
		"method": "Turbidimetry / Pyrogallol Red",
		"tat_hours": 6,
		"cost": 400,
		"report_format": "Standard",
		"parameters": [
			_p("Total Volume", "24HR_VOL", "mL", order=1, decimals=0),
			_p("Urine Protein", "24HR_PROT", "mg/24h", order=2, bold=1, decimals=0),
		],
		"reference_ranges": [
			_rr("Urine Protein", nmin=None, nmax=150, display="Normal: <150 mg/24h"),
		],
	},

	{
		"test_name": "Urine Pregnancy Test (UPT)",
		"test_code": "UPT",
		"department": "Clinical Pathology",
		"sample_type": "Urine (First Morning)",
		"method": "Immunochromatographic (ICT)",
		"tat_hours": 1,
		"cost": 150,
		"report_format": "Standard",
		"parameters": [_p("Urine Pregnancy Test", "UPT", rtype="Positive-Negative", order=1, bold=1)],
		"reference_ranges": [_rr("Urine Pregnancy Test", normal_text="Negative")],
	},

	# =====================================================================
	# ADDITIONAL SPECIAL TESTS
	# =====================================================================
	{
		"test_name": "Lead (Blood)",
		"test_code": "LEAD",
		"department": "Special Tests",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Atomic Absorption Spectrophotometry",
		"tat_hours": 72,
		"cost": 1500,
		"is_outsourced": 1,
		"report_format": "Standard",
		"parameters": [_p("Blood Lead", "LEAD", "µg/dL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Blood Lead", nmin=None, nmax=5, display="Acceptable: <5 | Elevated: ≥5"),
		],
	},

	{
		"test_name": "Mercury (Blood)",
		"test_code": "MERCURY",
		"department": "Special Tests",
		"sample_type": "Whole Blood (EDTA)",
		"method": "Atomic Absorption Spectrophotometry",
		"tat_hours": 72,
		"cost": 1500,
		"is_outsourced": 1,
		"report_format": "Standard",
		"parameters": [_p("Blood Mercury", "MERCURY", "µg/L", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Blood Mercury", nmin=None, nmax=10, display="Normal: <10 µg/L"),
		],
	},

	{
		"test_name": "HIV Viral Load (Quantitative PCR)",
		"test_code": "HIVVL",
		"department": "Virology & Molecular",
		"sample_type": "Serum (Plain)",
		"method": "Real-time PCR",
		"tat_hours": 72,
		"cost": 4500,
		"is_outsourced": 1,
		"report_format": "Standard",
		"parameters": [
			_p("HIV RNA", "HIVVL", "copies/mL", order=1, bold=1, decimals=0),
			_p("Log Value", "HIV_LOG", "log10 copies/mL", order=2, decimals=2),
			_p("Interpretation", "HIV_INTERP", rtype="Text", order=3, bold=1),
		],
		"reference_ranges": [
			_rr("HIV RNA", nmin=None, nmax=20, display="Not Detected: <20 copies/mL"),
		],
	},

	{
		"test_name": "Procalcitonin (PCT)",
		"test_code": "PCT",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 4,
		"cost": 2000,
		"report_format": "Standard",
		"parameters": [_p("Procalcitonin", "PCT", "ng/mL", order=1, bold=1, decimals=3)],
		"reference_ranges": [
			_rr("Procalcitonin", nmin=None, nmax=0.05,
				display="Normal: <0.05 | Bacterial infection likely: >0.5 | Sepsis: >2.0"),
		],
	},

	{
		"test_name": "Serum Osmolality",
		"test_code": "OSMO",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Freezing Point Depression",
		"tat_hours": 6,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("Serum Osmolality", "OSMO", "mOsm/kg", order=1, decimals=0)],
		"reference_ranges": [_rr("Serum Osmolality", nmin=275, nmax=295, display="275–295")],
	},

	{
		"test_name": "Aldosterone",
		"test_code": "ALDO",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 48,
		"cost": 1800,
		"report_format": "Standard",
		"parameters": [_p("Aldosterone", "ALDO", "ng/dL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Aldosterone", nmin=4, nmax=31, display="4–31 ng/dL (upright position)"),
		],
	},

	{
		"test_name": "Renin",
		"test_code": "RENIN",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 48,
		"cost": 2000,
		"report_format": "Standard",
		"parameters": [_p("Renin", "RENIN", "µIU/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [
			_rr("Renin", nmin=2.8, nmax=39.9, display="2.8–39.9 µIU/mL (upright position)"),
		],
	},

	{
		"test_name": "Parathyroid Hormone (PTH)",
		"test_code": "PTH",
		"department": "Endocrinology",
		"sample_type": "Serum (Plain)",
		"method": "ECLIA",
		"tat_hours": 24,
		"cost": 1500,
		"report_format": "Standard",
		"parameters": [_p("PTH (Intact)", "PTH", "pg/mL", order=1, bold=1, decimals=1)],
		"reference_ranges": [_rr("PTH (Intact)", nmin=15, nmax=65, display="15–65")],
	},

	{
		"test_name": "Vitamin A (Retinol)",
		"test_code": "VITA",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "HPLC",
		"tat_hours": 48,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("Vitamin A", "VITA", "µg/dL", order=1, decimals=1)],
		"reference_ranges": [_rr("Vitamin A", nmin=30, nmax=80, display="30–80")],
	},

	{
		"test_name": "Vitamin E (Tocopherol)",
		"test_code": "VITE",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "HPLC",
		"tat_hours": 48,
		"cost": 1200,
		"report_format": "Standard",
		"parameters": [_p("Vitamin E", "VITE", "mg/dL", order=1, decimals=2)],
		"reference_ranges": [_rr("Vitamin E", nmin=0.5, nmax=1.8, display="0.5–1.8")],
	},

	{
		"test_name": "Vitamin K",
		"test_code": "VITK",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "HPLC",
		"tat_hours": 72,
		"cost": 2000,
		"is_outsourced": 1,
		"report_format": "Standard",
		"parameters": [_p("Vitamin K", "VITK", "ng/mL", order=1, decimals=2)],
		"reference_ranges": [_rr("Vitamin K", nmin=0.2, nmax=3.2, display="0.2–3.2")],
	},

	{
		"test_name": "Ammonia (Blood)",
		"test_code": "NH3",
		"department": "Biochemistry",
		"sample_type": "Serum (Plain)",
		"method": "Enzymatic",
		"tat_hours": 4,
		"cost": 800,
		"report_format": "Standard",
		"parameters": [_p("Blood Ammonia", "NH3", "µg/dL", order=1, decimals=0)],
		"reference_ranges": [
			_rr("Blood Ammonia", nmin=None, nmax=50, cmin=None, cmax=200, display="Normal: <50 µg/dL"),
		],
	},

	{
		"test_name": "Lactate (Blood)",
		"test_code": "LACTATE",
		"department": "Biochemistry",
		"sample_type": "Plasma (Fluoride)",
		"method": "Enzymatic",
		"tat_hours": 2,
		"cost": 600,
		"report_format": "Standard",
		"parameters": [_p("Blood Lactate", "LACTATE", "mmol/L", order=1, decimals=1)],
		"reference_ranges": [
			_rr("Blood Lactate", nmin=0.5, nmax=2.2, cmin=None, cmax=5.0, display="0.5–2.2"),
		],
	},

	{
		"test_name": "Uric Acid (Urine 24h)",
		"test_code": "24HRUA",
		"department": "Clinical Pathology",
		"sample_type": "Urine (First Morning)",
		"method": "Enzymatic Colorimetric",
		"tat_hours": 6,
		"cost": 400,
		"report_format": "Standard",
		"parameters": [
			_p("Total Volume", "24HRUA_VOL", "mL", order=1, decimals=0),
			_p("Uric Acid", "24HRUA", "mg/24h", order=2, bold=1, decimals=0),
		],
		"reference_ranges": [
			_rr("Uric Acid", nmin=250, nmax=750, display="250–750 mg/24h"),
		],
	},

	{
		"test_name": "Creatinine Clearance (24h)",
		"test_code": "CRCL",
		"department": "Clinical Pathology",
		"sample_type": "Urine (First Morning)",
		"method": "Jaffe Method + Calculation",
		"tat_hours": 6,
		"cost": 500,
		"report_format": "Standard",
		"parameters": [
			_p("Urine Volume", "CRCL_VOL", "mL/24h", order=1, decimals=0),
			_p("Urine Creatinine", "CRCL_UCREAT", "mg/dL", order=2, decimals=1),
			_p("Serum Creatinine", "CRCL_SCREAT", "mg/dL", order=3, decimals=2),
			_p("Creatinine Clearance", "CRCL", "mL/min", order=4, bold=1, decimals=1,
			   calc=1, formula="(CRCL_UCREAT * CRCL_VOL) / (CRCL_SCREAT * 1440)"),
		],
		"reference_ranges": [
			_rr("Creatinine Clearance", "Male",   nmin=97, nmax=137, display="97–137"),
			_rr("Creatinine Clearance", "Female", nmin=88, nmax=128, display="88–128"),
		],
	},
]
