"""
ArogyaPath Phase 9 — Lab Test Panel seed data (25 panels).
Modelled on Dr Lal PathLabs Swasthfit, Thyrocare Aarogyam, SRL, Metropolis packages.
"""

LAB_TEST_PANELS = [
	{
		"panel_name": "Basic Health Checkup",
		"panel_code": "BASIC-HEALTH",
		"cost": 699,
		"description": "Essential screening: CBC, blood sugar, urine routine, liver and kidney tests.",
		"test_codes": ["CBC", "GLUF", "URME", "LFT", "KFT"],
	},
	{
		"panel_name": "Standard Health Checkup",
		"panel_code": "STD-HEALTH",
		"cost": 999,
		"description": "Standard annual health check with thyroid, diabetes, and organ function.",
		"test_codes": ["CBC", "HBA1C", "LFT", "KFT", "LIPID", "TFT", "URME"],
	},
	{
		"panel_name": "Full Body Checkup Basic (64 Tests)",
		"panel_code": "FULL-BODY-1",
		"cost": 1299,
		"description": "Thyrocare Aarogyam-style basic full body: CBC, diabetes, LFT, KFT, lipid, thyroid, urine.",
		"test_codes": ["CBC", "ESR", "GLUF", "HBA1C", "LFT", "KFT", "LIPID", "TFT", "URME", "IRON"],
	},
	{
		"panel_name": "Full Body Checkup Advanced (85 Tests)",
		"panel_code": "FULL-BODY-2",
		"cost": 1699,
		"description": "Full Body Basic + iron studies, Vitamin B12, Vitamin D3, CRP.",
		"test_codes": ["CBC", "ESR", "GLUF", "HBA1C", "LFT", "KFT", "LIPID", "TFT", "URME",
					   "IRON", "FERR", "VITB12", "VITD", "CRP"],
	},
	{
		"panel_name": "Full Body Checkup Complete (96 Tests)",
		"panel_code": "FULL-BODY-3",
		"cost": 1999,
		"description": "Advanced package + cardiac risk markers, electrolytes, uric acid, folate.",
		"test_codes": ["CBC", "ESR", "GLUF", "HBA1C", "LFT", "KFT", "LIPID", "TFT", "URME",
					   "IRON", "FERR", "VITB12", "VITD", "CRP", "ELEC", "UA", "FOLATE", "HSCRP"],
	},
	{
		"panel_name": "Aarogyam Gold — 117 Tests",
		"panel_code": "AAROGYAM-GOLD",
		"cost": 3999,
		"description": "Comprehensive wellness package modelled on Thyrocare Aarogyam 1.8: full body + toxic elements + hormones + cardiac elite.",
		"test_codes": ["CBC", "ESR", "GLUF", "HBA1C", "LFT", "KFT", "LIPID", "TFT", "FTFT",
					   "URME", "IRON", "FERR", "VITB12", "VITD", "CRP", "HSCRP", "ELEC",
					   "UA", "FOLATE", "MG", "HOMO", "TROPI", "CPKMB",
					   "PRL", "FSH", "LH", "TESTO", "E2", "INSULIN"],
	},
	{
		"panel_name": "Thyroid Basic (T3/T4/TSH)",
		"panel_code": "THYROID-BASIC",
		"cost": 349,
		"description": "Basic thyroid function: T3, T4, TSH.",
		"test_codes": ["TFT"],
	},
	{
		"panel_name": "Thyroid Complete",
		"panel_code": "THYROID-COMP",
		"cost": 849,
		"description": "Complete thyroid panel: FT3, FT4, TSH + Anti-TPO antibody.",
		"test_codes": ["FTFT", "ANTITPO"],
	},
	{
		"panel_name": "Diabetes Screening",
		"panel_code": "DIABETES-BASIC",
		"cost": 499,
		"description": "Blood glucose fasting, PP, HbA1c, urine routine.",
		"test_codes": ["GLUF", "GLUPP", "HBA1C", "URME"],
	},
	{
		"panel_name": "Diabetes Complete",
		"panel_code": "DIABETES-COMP",
		"cost": 1299,
		"description": "Comprehensive diabetic profile: glucose, HbA1c, insulin, kidney, lipid, microalbumin.",
		"test_codes": ["GLUF", "GLUPP", "HBA1C", "GTT", "INSULIN", "KFT", "LIPID", "MICROALB", "URME"],
	},
	{
		"panel_name": "Cardiac Basic",
		"panel_code": "CARDIAC-BASIC",
		"cost": 1499,
		"description": "Cardiac risk screening: lipid profile, hs-CRP, CPK-MB, Troponin I.",
		"test_codes": ["LIPID", "HSCRP", "CPKMB", "TROPI"],
	},
	{
		"panel_name": "Cardiac Complete",
		"panel_code": "CARDIAC-COMP",
		"cost": 2999,
		"description": "Advanced cardiac risk: lipid + hs-CRP + homocysteine + troponin I + D-Dimer.",
		"test_codes": ["LIPID", "HSCRP", "CPKMB", "TROPI", "HOMO", "DDIMER"],
	},
	{
		"panel_name": "Senior Man Package",
		"panel_code": "SENIOR-MAN",
		"cost": 2199,
		"description": "Dr Lal-style senior man package: CBC, LFT, KFT, lipid, thyroid, PSA, vitamins, HbA1c, urine.",
		"test_codes": ["CBC", "LFT", "KFT", "LIPID", "TFT", "PSA", "VITD", "VITB12", "HBA1C", "URME", "ESR"],
	},
	{
		"panel_name": "Senior Woman Package",
		"panel_code": "SENIOR-WOMAN",
		"cost": 2199,
		"description": "Dr Lal-style senior woman package: CBC, LFT, KFT, lipid, thyroid, CA-125, vitamins, HbA1c, urine.",
		"test_codes": ["CBC", "LFT", "KFT", "LIPID", "TFT", "CA125", "VITD", "VITB12", "HBA1C", "URME", "ESR"],
	},
	{
		"panel_name": "Fever Panel",
		"panel_code": "FEVER-PANEL",
		"cost": 1499,
		"description": "Comprehensive fever workup: CBC, CRP, Widal, Dengue NS1+IgM/IgG, Malaria, blood culture.",
		"test_codes": ["CBC", "CRP", "TYPHOID", "DENGUE", "MALARIA", "BLOODCS"],
	},
	{
		"panel_name": "Anaemia Profile",
		"panel_code": "ANEMIA-PANEL",
		"cost": 999,
		"description": "Complete anaemia workup: CBC, peripheral smear, iron studies, ferritin, B12, folate, reticulocyte.",
		"test_codes": ["CBC", "PBS", "IRON", "FERR", "VITB12", "FOLATE", "RETIC"],
	},
	{
		"panel_name": "Liver Function Complete",
		"panel_code": "LIVER-PANEL",
		"cost": 1299,
		"description": "Comprehensive liver: LFT + GFT + viral markers (HBsAg, HCV).",
		"test_codes": ["LFT", "HBSAG", "VIRAL4"],
	},
	{
		"panel_name": "Kidney Function Complete",
		"panel_code": "KIDNEY-PANEL",
		"cost": 1499,
		"description": "Complete kidney workup: KFT, urine R/M, microalbumin, electrolytes, urine culture.",
		"test_codes": ["KFT", "URME", "MICROALB", "ELEC", "URINECS"],
	},
	{
		"panel_name": "Female Hormone Panel",
		"panel_code": "HORMONE-FEMALE",
		"cost": 2499,
		"description": "Complete female hormone profile: FSH, LH, Estradiol, Progesterone, Prolactin, Testosterone.",
		"test_codes": ["FSH", "LH", "E2", "PROG", "PRL", "TESTO"],
	},
	{
		"panel_name": "Male Hormone Panel",
		"panel_code": "HORMONE-MALE",
		"cost": 1999,
		"description": "Male hormone profile: Testosterone total, FSH, LH, Prolactin, DHEA-S.",
		"test_codes": ["TESTO", "FSH", "LH", "PRL", "DHEAS"],
	},
	{
		"panel_name": "PCOD / PCOS Screen",
		"panel_code": "PCOD-PANEL",
		"cost": 2999,
		"description": "PCOD/PCOS workup: FSH, LH, Prolactin, Testosterone, DHEA-S, Insulin, TSH, Anti-TPO.",
		"test_codes": ["FSH", "LH", "PRL", "TESTO", "DHEAS", "INSULIN", "TSH", "ANTITPO", "E2"],
	},
	{
		"panel_name": "Antenatal Basic",
		"panel_code": "PRENATAL-BASIC",
		"cost": 999,
		"description": "Basic antenatal screen: CBC, blood sugar fasting, viral markers, urine R/M.",
		"test_codes": ["CBC", "GLUF", "VIRAL4", "URME"],
	},
	{
		"panel_name": "Autoimmune Screen",
		"panel_code": "AUTOIMMUNE",
		"cost": 3499,
		"description": "Comprehensive autoimmune panel: ANA, Anti-CCP, RA Factor, CRP, ESR, ASO.",
		"test_codes": ["ANA", "ANTICCP", "RAF", "CRP", "ESR", "ASO"],
	},
	{
		"panel_name": "Vitamin Deficiency Panel",
		"panel_code": "VITAMIN-PANEL",
		"cost": 1299,
		"description": "Common vitamin deficiency screen: Vitamin D3, B12, Folic Acid, Iron Studies.",
		"test_codes": ["VITD", "VITB12", "FOLATE", "IRON", "FERR"],
	},
	{
		"panel_name": "Tumor Markers Basic",
		"panel_code": "TUMOR-BASIC",
		"cost": 2999,
		"description": "Common tumor marker screen: AFP, CEA, CA 19-9. Add PSA for men or CA-125 for women.",
		"test_codes": ["AFP", "CEA", "CA199", "PSA", "CA125"],
	},
]
